# Master Technology Bar - Docker Compose
# Simple configuration following YAGNI principle

version: '3.8'

services:
  # Main application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: master-tech-bar
    ports:
      - "8000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Development mode (when needed)
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: master-tech-bar-dev
    ports:
      - "8001:8000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev
    command: npm run dev